let allTriggerAnswersJSON = `[
{"müde sein | mehr Sport treiben" : ["Was soll ich nur tun? Ich bin immer so müde.", "Du solltest mehr Sport treiben.", "Ich treibe doch schon mehr Sport.", "Dann solltest du auf jeden Fall zum Arzt gehen!"],
"depressiv sein | eine Therapie machen" : ["Was soll ich nur tun? Ich bin immer so depressiv.", "Du solltest eine Therapie machen.", "Ich mache doch schon eine Therapie.", "Dann solltest du auf jeden Fall zum Arzt gehen!"],
"nervös sein | meditieren" : ["Was soll ich nur tun? Ich bin immer so nervös.", "Du solltest meditieren.", "Ich meditiere doch schon.", "Dann solltest du auf jeden Fall zum Arzt gehen!"],
"vergesslich sein | weniger arbeiten" : ["Was soll ich nur tun? Ich bin immer so vergesslich.", "Du solltest weniger arbeiten.", "Ich arbeite doch schon weniger.", "Dann solltest du auf jeden Fall zum Arzt gehen!"],
"sich schnell aufregen | öfter einen Schnaps trinken" : ["Was soll ich nur tun? Ich rege mich immer so schnell auf.", "Du solltest öfter einen Schnaps trinken.", "Ich trinke doch schon öfter einen Schnaps.", "Dann solltest du auf jeden Fall zum Arzt gehen!"],
"gestresst sein | öfter Urlaub machen" : ["Was soll ich nur tun? Ich bin immer so gestresst.", "Du solltest öfter Urlaub machen.", "Ich mache doch schon öfter Urlaub.", "Dann solltest du auf jeden Fall zum Arzt gehen!"],
"schnell zunehmen | gesünder essen" : ["Was soll ich nur tun? Ich nehme immer so schnell zu.", "Du solltest gesünder essen.", "Ich esse doch schon gesünder.", "Dann solltest du auf jeden Fall zum Arzt gehen!"],
"angespannt sein | mehr Yoga machen" : ["Was soll ich nur tun? Ich bin immer so angespannt.", "Du solltest Yoga machen.", "Ich mache doch schon Yoga.", "Dann solltest du auf jeden Fall zum Arzt gehen!"],
"traurig sein | öfter spazieren gehen" : ["Was soll ich nur tun? Ich bin immer so traurig.", "Du solltest öfter spazieren gehen.", "Ich gehe doch schon oft spazieren.", "Dann solltest du auf jeden Fall zum Arzt gehen!"],
"antriebslos sein | eine Entspannungskur machen" : ["Was soll ich nur tun? Ich bin immer so antriebslos.", "Du solltest eine Entspannungskur machen.", "Ich mache doch schon eine Entspannungskur.", "Dann solltest du auf jeden Fall zum Arzt gehen!"]}
]`;

const triggers = ['müde sein | mehr Sport treiben', 'depressiv sein | eine Therapie machen', 'nervös sein | meditieren', 'vergesslich sein | weniger arbeiten', 'sich schnell aufregen | öfter einen Schnaps trinken', 'gestresst sein | öfter Urlaub machen', 'schnell zunehmen | gesünder essen', 'angespannt sein | mehr Yoga machen', 'traurig sein | öfter spazieren gehen', 'antriebslos sein | eine Entspannungskur machen'];