let allTriggerAnswersJSON = `[
{"Das Essen riecht gut." : ["Das Essen riecht gut.", "Das ist gut riechendes Essen.", "Ich liebe gut riechendes Essen.", "Vor allem, wenn es gut riecht."],
"Der Nachtisch schmeckt lecker." : ["Der Nachtisch schmeckt lecker.", "Das ist lecker schmeckender Nachtisch.", "Ich liebe lecker schmeckenden Nachtisch.", "Vor allem, wenn er lecker schmeckt."],
"Der Zug fährt langsam." : ["Der Zug fährt langsam.", "Das ist ein langsam fahrender Zug.", "Ich liebe langsam fahrende Züge.", "Vor allem, wenn sie langsam fahren."],
"Der Baum brennt." : ["Der Baum brennt.", "Das ist ein brennender Baum.", "Ich liebe keine brennenden Bäume.", "Vor allem, wenn sie nicht brennen."],
"Das Auto fährt schnell." : ["Das Auto fährt schnell.", "Das ist ein schnell fahrendes Auto.", "Ich liebe fahrende Autos.", "Vor allem, wenn sie schnell fahren."],
"Der Iltis stinkt." : ["Der Iltis stinkt.", "Das ist ein stinkender Iltis.", "Ich liebe stinkende Iltisse.", "Vor allem, wenn sie stinken."],
"Die Säge singt." : ["Die Säge singt.", "Das ist eine singende Säge.", "Ich liebe singende Sägen.", "Vor allem, wenn sie singen."],
"Der Mensch denkt." : ["Der Mensch denkt.", "Das ist ein denkender Mensch.", "Ich liebe denkende Menschen.", "Vor allem, wenn sie gute Ideen haben."],
"Der Typ stört." : ["Der Typ stört.", "Das ist ein störender Typ.", "Ich liebe störende Typen.", "Vor allem, wenn sie stören."],
"Der Schwan stirbt." : ["Der Schwan stirbt.", "Das ist ein sterbender Schwan.", "Ich liebe sterbende Schwäne.", "Vor allem, wenn sie sterben."],
"Das Huhn wurde gekocht." : ["Das Huhn wurde gekocht.", "Das ist ein gekochtes Huhn.", "Ich liebe gekochte Hühner.", "Vor allem, wenn sie gekocht sind."],
"Der Sohn wurde verloren." : ["Der Sohn ist verloren.", "Das ist ein verlorener Sohn.", "Ich liebe verlorene Söhne.", "Vor allem, wenn sie verloren sind."],
"Der Tag ist verloren." : ["Der Tag ist verloren.", "Das ist ein verlorener Tag.", "Ich liebe verlorene Tage.", "Vor allem, wenn sie verloren sind."],
"Der Mann wurde geschieden." : ["Der Mann wurde geschieden.", "Das ist ein geschiedener Mann.", "Ich liebe geschiedene Männer.", "Vor allem, wenn sie geschieden."],
"Das Bier wurde frisch gezapft." : ["Das Bier wurde frisch gezapft.", "Das ist ein frisch gezapftes Bier.", "Ich liebe frisch gezapftes Bier.", "Vor allem, wenn es frisch gezapft ist."],
"Die Sitzung wurde unterbrochen." : ["Die Sitzung wurde unterbrochen.", "Das ist eine unterbrochene Sitzung.", "Ich liebe unterbrochene Sitzungen.", "Vor allem, wenn sie unterbrochen sind."],
"Der Ausweis wurde gefälscht." : ["Der Ausweis wurde gefälscht.", "Das ist ein gefälschter Ausweis.", "Ich liebe gefälschte Ausweise.", "Vor allem, wenn sie gefälscht sind."],
"Das Hemd wurde frisch gewaschen." : ["Das Hemd wurde frisch gewaschen.", "Das ist ein frisch gewaschenes Hemd.", "Ich liebe frisch gewaschene Hemden.", "Vor allem, wenn sie frisch gewaschen sind."],
"Das Auto wurde neu gekauft." : ["Das Auto wurde neu gekauft.", "Das ist ein neu gekauftes Auto.", "Ich liebe neu gekaufte Autos.", "Vor allem, wenn sie neu gekauft sind."],
"Der Fisch wurde frisch gefangen." : ["Der Fisch wurde frisch gefangen.", "Das ist ein frisch gefangener Fisch.", "Ich liebe frisch gefangene Fische.", "Vor allem, wenn sie frisch gefangen sind."],
"Die Honda wurde gut gepflegt." : ["Die Honde wurde gut gepflegt.", "Das ist eine gut gepflegte Honda.", "Ich liebe gut gepflegte Hondas.", "Vor allem, wenn sie gut gepflegt sind."],
"Das Wasser kocht." : ["Das Wasser kocht.", "Das ist kochendes Wasser.", "Ich liebe kochendes Wasser.", "Vor allem, wenn es kocht."],
"Das Wasser wurde gekocht." : ["Das Wasser wurde gekocht.", "Das ist gekochtes Wasser.", "Ich liebe gekochtes Wasser.", "Vor allem, wenn es gekocht ist."],
"Der Weizen wurde frisch geerntet." : ["Der Weizen wurde frisch geerntet.", "Das ist frisch geernteter Weizen.", "Ich liebe frisch geernteten Weizen.", "Vor allem, wenn er frisch geerntet ist."],
"Der Bär tanzt." : ["Der Bär tanzt.", "Das ist ein tanzender Bär.", "Ich liebe tanzende Bären.", "Vor allem, wenn sie tanzen."],
"Das Kind schreit." : ["Das Kind schreit.", "Das ist ein schreiendes Kind.", "Ich liebe schreiende Kinder.", "Vor allem, wenn sie schreien."],
"Die Banane wurde geschält." : ["Die Banane wurde geschält.", "Das ist eine geschälte Banane.", "Ich liebe geschälte Bananen.", "Vor allem, wenn sie geschält sind."],
"Das Versprechen wurde gebrochen." : ["Das Versprechen wurde gebrochen.", "Das ist ein gebrochenes Versprechen.", "Ich liebe gebrochene Versprechen.", "Vor allem, wenn sie gebrochen sind."],
"Der Ast fällt herab." : ["Der Ast fällt herab.", "Das ist ein herabfallender Ast.", "Ich liebe herabfallende Äste.", "Vor allem, wenn sie herabfallen."],
"Der Typ ist gestört." : ["Der Typ ist gestört.", "Das ist ein gestörter Typ.", "Ich liebe gestörte Typen.", "Vor allem, wenn sie gestört sind."],
"Das Bett wurde frisch gemacht." : ["Das Bett ist frisch gemacht.", "Das ist ein frisch gemachtes Bett.", "Ich liebe frisch gemachte Betten.", "Vor allem, wenn sie frisch gemacht sind."],
"Der Papagei kann sprechen." : ["Der Papagei spricht.", "Das ist ein sprechender Papagei.", "Ich liebe sprechende Papageien.", "Vor allem, wenn sie sprechen."],
"Die Aussage verletzt mich." : ["Die Aussage verletzt.", "Das ist eine verletzende Aussage.", "Ich liebe verletzende Aussagen.", "Vor allem, wenn sie verletzen."]}
]`;

const triggers = ['Das Essen riecht gut.', 'Der Nachtisch schmeckt lecker.', 'Der Zug fährt langsam.', 'Der Baum brennt.', 'Das Auto fährt schnell.', 'Der Iltis stinkt.', 'Die Säge singt.', 'Der Mensch denkt.', 'Der Typ stört.', 'Der Schwan stirbt.', 'Das Huhn wurde gekocht.', 'Der Sohn wurde verloren.', 'Der Tag ist verloren.', 'Der Mann wurde geschieden.', 'Das Bier wurde frisch gezapft.', 'Die Sitzung wurde unterbrochen.', 'Der Ausweis wurde gefälscht.', 'Das Hemd wurde frisch gewaschen.', 'Das Auto wurde neu gekauft.', 'Der Fisch wurde frisch gefangen.', 'Die Honda wurde gut gepflegt.', 'Das Wasser kocht.', 'Das Wasser wurde gekocht.', 'Der Weizen wurde frisch geerntet.', 'Der Bär tanzt.', 'Das Kind schreit.', 'Die Banane wurde geschält.', 'Das Versprechen wurde gebrochen.', 'Der Ast fällt herab.', 'Der Typ ist gestört.', 'Das Bett wurde frisch gemacht.', 'Der Papagei kann sprechen.', 'Die Aussage verletzt mich.'];