let allTriggerAnswersJSON = `[
{"es nicht mögen | Klamotten kaufen" : ["Kaufst du ein?", "Nein. Ich mag es nicht, einzukaufen.", "Warum magst du es denn nicht, einzukaufen?", "Weil ich es schlicht und einfach nicht mag."],
"es leid sein | alles organisieren" : ["Organisiert du alles?", "Nein. Ich bin es leid, alles zu organisieren.", "Warum bist du es denn leid, alles zu organisieren?", "Weil ich es schlicht und einfach leid bin."],
"es ist nicht nötig | aufräumen" : ["Räumst du auf?", "Nein. Es ist nicht nötig, aufzuräumen.", "Warum ist es denn nicht nötig, aufzuräumen?", "Weil es schlicht und einfach nicht nötig ist."],
"es hassen | kochen" : ["Kochst du?", "Nein. Ich hasse es, zu kochen.", "Warum hasst du es, zu kochen?", "Weil ich es schlicht und einfach hasse."],
"es fühlt sich nicht gut an | die Arbeit stehen lassen" : ["Lässt du die Arbeit stehen?", "Nein, es fühlt sich nicht gut an, die Arbeit stehen zu lassen.", "Warum fühlt es sich denn nicht gut an, die Arbeit stehen zu lassen?", "Weil es sich schlicht und einfach nicht gut anfühlt."],
"es macht keinen Spaß | putzen" : ["Putzt du?", "Nein, es macht keinen Spaß, zu putzen.", "Warum macht es denn keinen Spaß, zu putzen?", "Weil es schlicht und einfach keinen Spaß macht."],
"es tut mir nicht gut | rauchen" : ["Rauchst du?", "Nein, es tut mir nicht gut, zu rauchen.", "Warum tut es dir denn nicht gut, zu rauchen?", "Weil es mir schlicht und einfach nicht gut tut."],
"es liegt mir gar nicht  | handwerklich arbeiten" : ["Arbeitest du handwerklich?", "Nein, es liegt mir gar nicht, handwerklich zu arbeiten.", "Warum liegt es dir denn nicht, handwerklich zu arbeiten?", "Weil es mir schlicht und einfach nicht liegt."],
"es ist so langweilig | für die Prüfung lernen" : ["Lernst du für die Prüfung?", "Nein, es ist so langweilig, für die Prüfung zu lernen.", "Warum ist es denn so langweilig, für die Prüfung zu lernen?", "Weil es schlicht und einfach langweilig ist."],
"es ist nicht selbstverständlich | alles alleine machen" : ["Machst du alles alleine?", "Nein, es ist nicht selbstverständlich, alles alleine zu machen.", "Warum ist es denn nicht selbstverständlich, alles alleine zu machen?", "Weil es einfach nicht selbstverständlich ist."]}
]`;

const triggers = ['es nicht mögen | Klamotten kaufen', 'es leid sein | alles organisieren', 'es ist nicht nötig | aufräumen', 'es hassen | kochen', 'es fühlt sich nicht gut an | die Arbeit stehen lassen', 'es macht keinen Spaß | putzen', 'es tut mir nicht gut | rauchen', 'es liegt mir gar nicht  | handwerklich arbeiten', 'es ist so langweilig | für die Prüfung lernen', 'es ist nicht selbstverständlich | alles alleine machen'];