let allTriggerAnswersJSON = `[
{"Das Wasser kann getrunken werden. (-bar)" : ["Man kann das Wasser trinken.", "Das Wasser ist nicht zu trinken.", "Das Wasser ist untrinkbar.", "Das Wasser lässt sich nicht trinken."],
"Die Unterschrift kann nicht gelesen werden. (-lich)" : ["Man kann die Unterschrift nicht lesen.", "Die Unterschrift ist nicht zu lesen.", "Die Unterschrift ist unleserlich.", "Die Unterschrift lässt sich nicht lesen."],
"Der Prophet kann nicht verstanden werden. (-lich, add an Umlaut)" : ["Man kann den Propheten nicht verstehen.", "Der Prophet ist nicht zu verstehen.", "Der Prophet ist unverständlich.", "Der Prophet lässt sich nicht verstehen."],
"Ihr Bein kann amputiert werden. (-bar)" : ["Man kann das Bein amputieren.", "Das Bein ist zu amputieren.", "Das Bein ist amputierbar.", "Das Bein lässt sich amputieren."],
"Das Passwort kann einfach geknackt werden. (-bar)" : ["Man kann das Passwort einfach knacken.", "Das Passwort ist zu knacken.", "Das Passwort ist knackbar.", "Das Passwort lässt sich knacken."],
"Das Ziel kann nicht erreicht werden. (-bar)" : ["Man kann das Ziel nicht erreichen.", "Das Ziel ist nicht zu erreichen.", "Das Ziel ist unerreichbar.", "Das Ziel lässt sich nicht erreichen."],
"Das Gesicht kann nicht erkannt werden. (-bar)" : ["Man kann das Gesicht nicht erkennen.", "Das Gesicht ist nicht zu erkennen.", "Das Gesicht ist unerkennbar.", "Das Gesicht lässt sich nicht erkennen."],
"Der Urlaub auf Bali kann nicht vergessen werden. (-lich)" : ["Man kann den Urlaub auf Bali nicht vergessen.", "Der Urlaub auf Bali ist nicht zu vergessen.", "Der Urlaub auf Bali ist unvergesslich.", "Der Urlaub lässt sich nicht vergessen."],
"Das Geschirr kann nicht zerbrochen werden. (-lich)" : ["Man kann das Geschirr nicht zerbrechen.", "Das Geschirr ist nicht zu zerbrechen.", "Das Geschirr ist unzerbrechlich.", "Das Geschirr lässt sich nicht zerbrechen."],
"Die Mona Lisa kann nicht verkauft werden. (-lich, add an Umlaut)" : ["Man kann die Mona Lisa nicht verkaufen.", "Die Mona Lisa ist nicht zu verkaufen.", "Die Mona Lisa ist unverkäuflich.", "Die Mona Lisa lässt sich nicht verkaufen."]}
]`;

const triggers = ['Das Wasser kann getrunken werden. (-bar)', 'Die Unterschrift kann nicht gelesen werden. (-lich)', 'Der Prophet kann nicht verstanden werden. (-lich, add an Umlaut)', 'Ihr Bein kann amputiert werden. (-bar)', 'Das Passwort kann einfach geknackt werden. (-bar)', 'Das Ziel kann nicht erreicht werden. (-bar)', 'Das Gesicht kann nicht erkannt werden. (-bar)', 'Der Urlaub auf Bali kann nicht vergessen werden. (-lich)', 'Das Geschirr kann nicht zerbrochen werden. (-lich)', 'Die Mona Lisa kann nicht verkauft werden. (-lich, add an Umlaut)'];