let allTriggerAnswersJSON = `[
{"Deutsch lernen | einen besseren Job finden" : ["Wozu lernst du eigentlich Deutsch?", "Um einen besseren Job zu finden.", "Das habe ich nicht verstanden. Warum lernst du nochmal Deutsch? -", "Damit ich einen besseren Job finde."],
"so früh schlafen gehen | morgen früh fit sein" : ["Wozu gehst du eigentlich so früh schlafen?", "Um morgen früh fit zu sein.", "Das habe ich nicht verstanden. Warum gehst du nochmal so früh schlafen?", "Damit ich morgen früh fit bin."],
"Geld sparen | in Urlaub fahren können" : ["Wozu sparst du eigentlich Geld?", "Um in Urlaub fahren zu können.", "Das habe ich nicht verstanden. Warum sparst du nochmal Geld?", "Damit ich in Urlaub fahren kann."],
"ein Fahrrad kaufen | nicht mehr mit der U-Bahn fahren müssen" : ["Wozu kaufst du eigentlich ein Fahrrad?", "Um nicht mehr mit der U-Bahn fahren zu müssen.", "Das habe ich nicht verstanden. Warum kaufst du nochmal ein Fahrrad?", "Damit ich nicht mehr mit der U-Bahn fahren muss."],
"nach Deutschland fliegen | einen Freund besuchen" : ["Wozu fliegst du eigentlich nach Deutschland?", "Um einen Freund zu besuchen.", "Das habe ich nicht verstanden. Warum fliegst du nochmal nach Deutschland?", "Damit ich einen Freund besuchen kann."],
"rechtzeitig losgehen | nicht zu spät kommen" : ["Wozu gehst du eigentlich rechtzeitig los?", "Um nicht zu spät zu kommen.", "Das habe ich nicht verstanden. Warum gehst du nochmal rechtzeitig los?", "Damit ich nicht zu spät komme."],
"so viel lernen | gut auf die Prüfung vorbereitet sein" : ["Wozu lernst du eigentlich so viel?", "Um gut auf die Prüfung vorbereitet zu sein.", "Das habe ich nicht verstanden. Warum lernst du nochmal so viel?", "Damit ich gut auf die Prüfung vorbereitet bin."],
"so viel reden | vom Thema ablenken" : ["Wozu redest du eigentlich so viel?", "Um vom Thema abzulenken.", "Das habe ich nicht verstanden. Warum redest du nochmal so viel?", "Damit ich vom Thema ablenken kann."],
"so viel Geld ausgeben | meinen Minderwertigkeitskomplex kompensieren" : ["Wozu gibt du eigentlich so viel Geld aus?", "Um meinen Minderwertigkeitskomplex zu kompensieren.", "Das habe ich nicht verstanden. Warum gibst du nochmal so viel Geld aus?", "Damit ich meinen Minderwertigkeitskomplex kompensieren kann."],
"der Vogel steht so früh auf | den Wurm fangen" : ["Wozu steht der Vogel eigentlich so früh auf?", "Um den Wurm zu fangen.", "Das habe ich nicht verstanden. Warum steht der Vogel nochmal so früh auf?", "Damit er den Wurm fangen kann/fängt."]}
]`;

const triggers = ['Deutsch lernen | einen besseren Job finden', 'so früh schlafen gehen | morgen früh fit sein', 'Geld sparen | in Urlaub fahren können', 'ein Fahrrad kaufen | nicht mehr mit der U-Bahn fahren müssen', 'nach Deutschland fliegen | einen Freund besuchen', 'rechtzeitig losgehen | nicht zu spät kommen', 'so viel lernen | gut auf die Prüfung vorbereitet sein', 'so viel reden | vom Thema ablenken', 'so viel Geld ausgeben | meinen Minderwertigkeitskomplex kompensieren', 'der Vogel steht so früh auf | den Wurm fangen'];
