let allTriggerAnswersJSON = `[
{"fernsehen | nicht" : ["Als Kind wollte ich immer fernsehen. Ich durfte aber nicht.", "Als Kind durfte ich auch nicht fernsehen.", "Aber wolltest du denn fernsehen?", "Nein, ich wollte als Kind nie wirklich fernsehen."],
"Zigaretten rauchen | kein" : ["Als Kind wollte ich immer Zigaretten rauchen. Ich durfte aber nicht.", "Als Kind durfte ich auch keine Zigaretten rauchen.", "Aber wolltest du denn Zigaretten rauchen?", "Nein, ich wollte als Kind nie wirklich Zigaretten rauchen."],
"Ballett tanzen | kein" : ["Als Kind wollte ich immer Ballett tanzen. Ich durfte aber nicht.", "Als Kind durfte ich auch kein Ballett tanzen.", "Aber wolltest du denn Ballett tanzen?", "Nein, ich wollte als Kind nie wirklich Ballett tanzen."],
"Süßigkeiten essen | kein" : ["Als Kind wollte ich immer Süßigkeiten essen. Ich durfte aber nicht.", "Als Kind durfte ich auch keine Süßigkeiten essen.", "Aber wolltest du denn Süßigkeiten essen?", "Nein, ich wollte als Kind nie wirklich Süßigkeiten essen."],
"Klavier spielen | kein" : ["Als Kind wollte ich immer Klavier spielen. Ich durfte aber nicht.", "Als Kind durfte ich auch kein Klavier spielen.", "Aber wolltest du denn Klavier spielen?", "Nein, ich wollte als Kind nie wirklich Klavier spielen."],
"Bier trinken | kein" : ["Als Kind wollte ich immer Bier trinken. Ich durfte aber nicht.", "Als Kind durfte ich auch kein Bier trinken.", "Aber wolltest du denn Bier trinken?", "Nein, ich wollte als Kind nie wirklich Bier trinken."],
"ohne Eltern in Urlaub fahren | nicht" : ["Als Kind wollte ich immer ohne Eltern in Urlaub fahren. Ich durfte aber nicht.", "Als Kind durfte ich auch nicht ohne Eltern in Urlaub fahren.", "Aber wolltest du denn ohne Eltern in Urlaub fahren?", "Nein, ich wollte als Kind nie wirklich ohne Eltern in Urlaub fahren."],
"in die Kirche gehen | nicht" : ["Als Kind wollte ich immer in die Kirche gehen. Ich durfte aber nicht.", "Als Kind durfte ich auch nicht in die Kirche gehen.", "Aber wolltest du denn in die Kirche gehen?", "Nein, ich wollte als Kind nie wirklich in die Kirche gehen."],
"Pommes essen | kein" : ["Als Kind wollte ich immer Pommes essen. Ich durfte aber nicht.", "Als Kind durfte ich auch keine Pommes essen.", "Aber wolltest du denn Pommes essen?", "Nein, ich wollte als Kind nie wirklich Pommes essen."],
"auf die Kirmes gehen | nicht" : ["Als Kind wollte ich immer auf die Kirmes gehen. Ich durfte aber nicht.", "Als Kind durfte ich auch nicht auf die Kirmes gehen.", "Aber wolltest du denn auf die Kirmes gehen?", "Nein, ich wollte als Kind nie wirklich auf die Kirmes gehen."]}
]`;

const triggers = ['fernsehen | nicht', 'Zigaretten rauchen | kein', 'Ballett tanzen | kein', 'Süßigkeiten essen | kein', 'Klavier spielen | kein', 'Bier trinken | kein', 'ohne Eltern in Urlaub fahren | nicht', 'in die Kirche gehen | nicht', 'Pommes essen | kein', 'auf die Kirmes gehen | nicht'];