let allTriggerAnswersJSON = `[
{"Deutsch lernen | einen besseren Job finden" : ["Warum lernst du eigentlich Deutsch?", "Ich lerne Deutsch, damit ich einen besseren Job finde.", "Das gefällt mir. Dann lerne ich jetzt auch Deutsch.", "Du Nachmacherin."],
"so früh schlafen gehen | morgen früh fit sein" : ["Warum gehst du eigentlich früh schlafen?", "Ich gehe früh schlafen, damit ich morgen früh fit bin.", "Das gefällt mir. Dann gehe ich jetzt auch früh schlafen.", "Du Nachmacherin."],
"Geld sparen | in Urlaub fahren können" : ["Warum sparst du eigentlich Geld?", "Ich spare Geld, damit ich in Urlaub fahren kann.", "Das gefällt mir. Dann spare ich jetzt auch Geld.", "Du Nachmacherin."],
"ein Fahrrad kaufen | nicht mehr mit der U-Bahn fahren müssen" : ["Warum kaufst du eigentlich ein Fahrrad?", "Ich kaufe ein Fahrrad, damit ich nicht mehr mit der U-Bahn fahren muss.", "Das gefällt mir. Dann kaufe ich jetzt auch ein Fahrrad.", "Du Nachmacherin."],
"nach Deutschland fliegen | einen Freund besuchen" : ["Warum fliegst du eigentlich nach Deutschland?", "Ich fliege nach Deutschland, damit ich einen Freund besuchen kann.", "Das gefällt mir. Dann fliege ich jetzt auch nach Deutschland.", "Du Nachmacherin."],
"rechtzeitig losgehen | nicht zu spät kommen" : ["Warum gehst du eigentlich rechtzeitig los?", "Ich gehe rechtzeitig los, damit ich nicht zu spät komme.", "Das gefällt mir. Dann gehe ich jetzt auch rechtzeitig los.", "Du Nachmacherin."],
"so viel lernen | gut auf die Prüfung vorbereitet sein" : ["Warum lernst du eigentlich so viel?", "Ich lerne so viel, damit ich gut auf die Prüfung vorbereitet bin.", "Das gefällt mir. Dann lerne ich jetzt auch so viel.", "Du Nachmacherin."],
"so viel reden  | vom Thema ablenken" : ["Warum redest du eigentlich so viel?", "Ich rede so viel, damit ich vom Thema ablenken kann.", "Das gefällt mir. Dann rede ich jetzt auch so viel.", "Du Nachmacherin."],
"so viel Geld ausgeben | meinen Minderwertigkeitskomplex kompensieren" : ["Warum gibt du eigentlich so viel Geld aus?", "Ich gebe so viel Geld aus, damit ich meinen Minderwertigkeitskomplex kompensieren kann.", "Das gefällt mir. Dann gebe ich jetzt auch so viel Geld aus.", "Du Nachmacherin."],
"der Vogel steht so früh auf | den Wurm fangen" : ["Warum steht der Vogel eigentlich so früh auf?", "Der Vogel steht so früh auf, damit er den Wurm fängt.", "Das gefällt mir. Dann stehe ich jetzt auch so früh auf.", "Du Nachmacherin."]}
]`;

const triggers = ['Deutsch lernen | einen besseren Job finden', 'so früh schlafen gehen | morgen früh fit sein', 'Geld sparen | in Urlaub fahren können', 'ein Fahrrad kaufen | nicht mehr mit der U-Bahn fahren müssen', 'nach Deutschland fliegen | einen Freund besuchen', 'rechtzeitig losgehen | nicht zu spät kommen', 'so viel lernen | gut auf die Prüfung vorbereitet sein', 'so viel reden  | vom Thema ablenken', 'so viel Geld ausgeben | meinen Minderwertigkeitskomplex kompensieren', 'der Vogel steht so früh auf | den Wurm fangen'];
