let allTriggerAnswersJSON = `[
{"er | im Lotto gewinnen" : ["Hat er wirklich im Lotto gewonnen?", "Es sieht ganz danach aus, als ob er im Lotto gewonnen hat.", "Es sieht ganz danach aus, als ob er im Lotto gewonnen hätte.", "Es sieht ganz danach aus, als hätte er im Lotto gewonnen."],
"sie | früh nach Hause gegangen sein" : ["Ist sie wirklich früh nach Hause gegangen?", "Es sieht ganz danach aus, als ob sie früh nach Hause gegangen ist.", "Es sieht ganz danach aus, als ob sie früh nach Hause gegangen wäre.", "Es sieht ganz danach aus, als wäre sie früh nach Hause gegangen."],
"sie | einen über den Durst trinken" : ["Hat sie wirklich einen über den Durst getrunken?", "Es sieht ganz danach aus, als ob sie einen über den Durst getrunken hat.", "Es sieht ganz danach aus, als ob sie einen über den Durst getrunken hätte.", "Es sieht ganz danach aus, als hätte sie einen über den Durst getrunken."],
"er | etwas vergessen" : ["Hat sie wirklich etwas vergessen?", "Es sieht ganz danach aus, als ob er etwas vergessen hat.", "Es sieht ganz danach aus, als ob er etwas vergessen hätte.", "Es sieht ganz danach aus, als hätte er etwas vergessen."],
"ihr | ein Gespenst sehen" : ["Haben wir wirklich ein Gespenst gesehen?", "Es sieht ganz danach aus, als ob ihr ein Gespenst gesehen habt.", "Es sieht ganz danach aus, als ob ihr ein Gespenst gesehen hättet.", "Es sieht ganz danach aus, als hättet ihr ein Gespenst gesehen."],
"jemand | gerad sterben" : ["Ist wirklich gerade jemand gestorben?", "Es sieht ganz danach aus, als ob gerade jemand gestorben ist.", "Es sieht ganz danach aus, als ob gerade jemand  gestorben wäre.", "Es sieht ganz danach aus, als wäre gerade jemand  gestorben."],
"jemand | gerade auferstehen" : ["Ist wirklich gerade jemand auferstanden?", "Es sieht ganz danach aus, als ob gerade jemand  auferstanden ist.", "Es sieht ganz danach aus, als ob gerade jemand auferstanden wäre.", "Es sieht ganz danach aus, als wäre gerade jemand auferstanden."],
"du | etwas soeben einfallen" : ["Ist dir wirklich gerade etwas eingefallen?", "Es sieht ganz danach aus, als ob dir gerade etwas eingefallen ist.", "Es sieht ganz danach aus, als ob dir gerade etwas eingefallen wäre.", "Es sieht ganz danach aus, als wäre dir gerade etwas eingefallen."],
"sie (pl.) | das Spiel gewonnen haben" : ["Hat sie wirklich das Spiel gewonnen?", "Es sieht ganz danach aus, als ob sie das Spiel gewonnen hat.", "Es sieht ganz danach aus, als ob sie das Spiel gewonnen hätte.", "Es sieht ganz danach aus, als hätte sie das Spiel gewonnen."],
"er | spurlos verschwinden" : ["Ist er wirklich spurlos verschwunden?", "Es sieht ganz danach aus, als ob er spurlos verschwunden ist.", "Es sieht ganz danach aus, als ob er spurlos verschwunden wäre.", "Es sieht ganz danach aus, als wäre er spurlos verschwunden."]}
]`;

const triggers = ['er | im Lotto gewinnen', 'sie | früh nach Hause gegangen sein', 'sie | einen über den Durst trinken', 'er | etwas vergessen', 'ihr | ein Gespenst sehen', 'jemand | gerad sterben', 'jemand | gerade auferstehen', 'du | etwas soeben einfallen', 'sie (pl.) | das Spiel gewonnen haben', 'er | spurlos verschwinden'];