let allTriggerAnswersJSON = `[
{"Deutsch lernen | einen besseren Job finden" : ["Warum lernst du eigentlich Deutsch?", "Ich lerne Deutsch, um einen besseren Job zu finden.", "Das gefällt mir. Dann lerne ich jetzt auch Deutsch.", "Du Nachmacher."],
"so früh schlafen gehen | morgen früh fit sein" : ["Warum gehst du eigentlich so früh schlafen?", "Ich gehe früh schlafen, um morgen früh fit zu sein.", "Das gefällt mir. Dann gehe ich jetzt auch so früh schlafen.", "Du Nachmacher."],
"Geld sparen | in Urlaub fahren können" : ["Warum sparst du eigentlich Geld?", "Ich spare Geld, um in Urlaub fahren zu können.", "Das gefällt mir. Dann spare ich jetzt auch Geld.", "Du Nachmacher."],
"ein Fahrrad kaufen | nicht mehr mit der U-Bahn fahren müssen" : ["Warum kaufst du eigentlich ein Fahrrad?", "Ich kaufe ein Fahrrad, um nicht mehr mit der U-Bahn fahren zu müssen.", "Das gefällt mir. Dann kaufe ich jetzt auch ein Fahrrad.", "Du Nachmacher."],
"nach Deutschland fliegen | einen Freund besuchen" : ["Warum fliegst du eigentlich nach Deutschland?", "Ich fliege nach Deutschland, um einen Freund zu besuchen.", "Das gefällt mir. Dann fliege ich jetzt auch nach Deutschland.", "Du Nachmacher."],
"rechtzeitig losgehen | nicht zu spät kommen" : ["Warum gehst du eigentlich rechtzeitig los?", "Ich gehe rechtzeitig los, um nicht zu spät zu kommen.", "Das gefällt mir. Dann gehe ich jetzt auch rechtzeitig los.", "Du Nachmacher."],
"so viel lernen | gut auf die Prüfung vorbereitet sein" : ["Warum lernst du eigentlich so viel?", "Ich lerne so viel, um mich gut auf die Prüfung vorzubereiten.", "Das gefällt mir. Dann lerne ich jetzt auch so viel.", "Du Nachmacher."],
"so viel reden | vom Thema ablenken" : ["Warum redest du eigentlich so viel?", "Ich rede so viel, um vom Thema abzulenken.", "Das gefällt mir. Dann rede ich jetzt auch so viel.", "Du Nachmacher."],
"so viel Geld ausgeben | meinen Minderwertigkeitskomplex kompensieren" : ["Warum gibt du eigentlich so viel Geld aus?", "Ich gebe so viel Geld aus, um meinen Minderwertigkeitskomplex zu kompensieren.", "Das gefällt mir. Dann gebe ich jetzt auch so viel Geld aus.", "Du Nachmacher."],
"der Vogel steht so früh auf | den Wurm fangen" : ["Warum steht der Vogel eigentlich so früh auf?", "Der Vogel steht so früh auf, um den Wurm zu fangen.", "Das gefällt mir. Dann stehe ich jetzt auch so früh auf.", "Du Nachmacher."]}
]`;

const triggers = ['Deutsch lernen | einen besseren Job finden', 'so früh schlafen gehen | morgen früh fit sein', 'Geld sparen | in Urlaub fahren können', 'ein Fahrrad kaufen | nicht mehr mit der U-Bahn fahren müssen', 'nach Deutschland fliegen | einen Freund besuchen', 'rechtzeitig losgehen | nicht zu spät kommen', 'so viel lernen | gut auf die Prüfung vorbereitet sein', 'so viel reden | vom Thema ablenken', 'so viel Geld ausgeben | meinen Minderwertigkeitskomplex kompensieren', 'der Vogel steht so früh auf | den Wurm fangen'];
