let allTriggerAnswersJSON = `[
{"gesund bleiben | Yoga üben" : ["Ich möchte gesund bleiben. Darum mache ich Yoga.", "Ich möchte gesund bleiben. Deswegen mache ich Yoga.", "Weil ich gesund bleiben möchte, mache ich Yoga.", "Um gesund zu bleiben, mache ich Yoga."],
"nicht stinken | jeden Tag duschen" : ["Ich möchte nicht stinken. Darum dusche ich jeden Tag.", "Ich möchte nicht stinken. Darum dusche ich jeden Tag.", "Weil ich nicht stinken möchte, dusche ich jeden Tag.", "Um nicht zu stinken, dusche ich jeden Tag."],
"nicht auf der Straße leben | jeden Tag zur Arbeit gehen" : ["Ich möchte nicht auf der Straße leben. Darum gehe ich jeden Tag zur Arbeit.", "Ich möchte nicht auf der Straße leben. Darum gehe ich jeden Tag zur Arbeit.", "Weil ich nicht auf der Straße leben möchte, gehe ich jeden Tag zur Arbeit.", "Um nicht auf der Straße zu leben, gehe ich jeden Tag zur Arbeit."],
"sich nicht einsam fühlen | unter Leute gehen" : ["Ich möchte mich nicht einsam fühlen. Darum gehe ich unter die Leute.", "Ich möchte mich nicht einsam fühlen. Deswegen gehe ich unter die Leute.", "Weil ich mich nicht einsam fühlen möchte, gehe ich nicht unter die Leute.", "Um mich nicht einsam zu fühlen, gehe ich unter die Leute."],
"Millionär werden | Lotto spielen" : ["Ich möchte Millionär werden. Darum spiele ich Lotto.", "Ich möchte Millionär werden. Darum spiele ich Lotto.", "Weil ich Millionär werden möchte, spiele ich Lotto.", "Um Millionär zu werden, spiele ich Lotto."],
"fit im Kopf bleiben | Kreuzworträtsel lösen" : ["Ich möchte fit im Kopf bleiben. Darum löse ich Kreuzworträtsel.", "Ich möchte fit im Kopf bleiben. Deswegen löse ich Kreuzworträtsel.", "Weil ich fit im Kopf bleiben möchte, löse ich Kreuzworträtsel.", "Um fit im Kopf zu bleiben, löse ich Kreuzworträtsel."],
"schnell wach werden | Kaffee trinken" : ["Ich möchte morgens schnell wach werden. Darum trinke ich Kaffee.", "Ich möchte morgens schnell wach werden. Deswegen trinke ich Kaffee.", "Weil ich morgens schnell wach werden möchte, trinke ich Kaffee.", "Um morgens schnell wach zu werden, trinke ich Kaffee."],
"gesund bleiben | jeden Tag joggen gehen" : ["Ich möchte fit bleiben. Darum gehe ich jeden Tag joggen.", "Ich möchte fit bleiben. Deswegen gehe ich jeden Tag joggen.", "Weil ich fit bleiben möchte, gehe ich jeden Tag joggen.", "Um fit zu bleiben, gehe ich jeden Tag joggen."],
"ausschlafen | die Vorhänge zuziehen" : ["Ich möchte ausschlafen. Darum ziehe ich die Vorhänge zu.", "Ich möchte ausschlafen. Deshalb ziehe ich die Vorhänge zu.", "Weil ich ausschlafen möchte, ziehe ich die Vorhänge zu.", "Um auszuschlafen, ziehe ich die Vorhänge zu."],
"100 Jahre alt werden  | viel Kombucha trinken" : ["Ich möchte 100 Jahre alt werden. Darum trinke ich viel Kombucha.", "Ich möchte 100 Jahre alt werden. Deswegen trinke ich viel Kombucha.", "Weil ich 100 Jahre alt werden möchte, trinke ich viel Kombucha.", "Um 100 Jahre alt zu werden, trinke ich viel Kombucha."]}
]`;

const triggers = ['gesund bleiben | Yoga üben', 'nicht stinken | jeden Tag duschen', 'nicht auf der Straße leben | jeden Tag zur Arbeit gehen', 'sich nicht einsam fühlen | unter Leute gehen', 'Millionär werden | Lotto spielen', 'fit im Kopf bleiben | Kreuzworträtsel lösen', 'schnell wach werden | Kaffee trinken', 'gesund bleiben | jeden Tag joggen gehen', 'ausschlafen | die Vorhänge zuziehen', '100 Jahre alt werden  | viel Kombucha trinken'];