let allTriggerAnswersJSON = `[
{"Zähne putzen" : ["Als ich noch ein Kind war, musste ich immer Zähne putzen.", "Und wie ist es heute? Musst du immer noch Zähne putzen?", "Heute habe ich kein Problem mehr mit Zähne putzen. Ich putze meine Zähne sehr gerne.", "Sieh an, sieh an. Die Zeiten ändern sich."],
"lange aufbleiben" : ["Als ich noch ein Kind war, wollte ich immer lange aufbleiben.", "Und wie ist es heute? Willst du immer noch lange aufbleiben?", "Heute gehe ich gerne früh ins Bett, dann schlafe ich besser.", "Sieh an, sieh an. Die Zeiten ändern sich."],
"zur Schule/Arbeit gehen" : ["Als ich noch ein Kind war, musste ich jeden Tag zur Schule gehen.", "Und wie ist es heute? Musst du heute immer noch jeden Tag zur Schule gehen?", "Heute muss ich nicht mehr zur Schule gehen, aber dafür muss ich jeden Tag zur Arbeit gehen. Das ist auch nicht viel besser.", "Sieh an, sieh an. Die Zeiten ändern sich."],
"mit dem Fahrrad zur Schule/zur Arbeit fahren" : ["Als ich noch ein Kind war, musste ich jeden Tag mit dem Fahrrad zur Schule fahren.", "Und wie ist es heute? Musst du immer noch jeden Tag zur Schule fahren?", "Nein, heute muss ich nicht mehr mit dem Fahrrad zur Schule fahren. Ich fahre zur Arbeit und zur Arbeit fahre ich immer mit dem Auto.", "Sieh an, sieh an. Die Zeiten ändern sich."],
"Süßigkeiten essen" : ["Als ich noch ein Kind war wollte ich immer Süßigkeiten essen.", "Und wie ist es heute? Willst du immer noch gerne Süßigkeiten essen?", "Heute esse ich nicht mehr so gerne Süßigkeiten, denn die sind nicht gut für meine Gesundheit.", "Sieh an, sieh an. Die Zeiten ändern sich."],
"vor dem Essen beten" : ["Als ich noch ein Kind war, musste ich immer vor dem Essen beten.", "Und wie ist es heute? Musst du immer noch vor dem Essen beten?", "Heute bin ich Atheist. Ich muss nicht mehr vor dem Essen beten.", "Sieh an, sieh an. Die Zeiten ändern sich."],
"zur Kirche/ in die Moschee/ in den Tempel gehen" : ["Als ich noch ein Kind war, musste ich jeden Sonntag zur Kirche gehen.", "Und wie ist es heute? Musst du immer noch jeden Sonntag zur Kirche gehen?", "Nein, heute kann nicht zur Kirche gehen wenn ich möchte, aber ich schlafe sonntags lieber.", "Sieh an, sieh an. Die Zeiten ändern sich."],
"Alkohol trinken" : ["Als ich noch ein Kind war, mochte ich keinen Alkohol.", "Und wie ist es heute? Magst du heute Alkohol?", "Ja, heute kann ich Alkohol trinken aber ich trinke nicht zu viel. Das leckt mir immer so auf den Kopf.", "Sieh an, sieh an. Die Zeiten ändern sich."],
"den Teller leer essen" : ["Als ich noch ein Kind war, musste ich immer meinen Teller leer essen.", "Und wie ist es heute? Musst du heute immer noch deinen Teller leer essen?", "Nein, heute muss ich meinen Teller nicht leer essen aber ich tue es gerne, denn ich hasse es Essen wegzuwerfen.", "Sieh an, sieh an. Die Zeiten ändern sich."]}
]`;

const triggers = ['Zähne putzen', 'lange aufbleiben', 'zur Schule/Arbeit gehen', 'mit dem Fahrrad zur Schule/zur Arbeit fahren', 'Süßigkeiten essen', 'vor dem Essen beten', 'zur Kirche/ in die Moschee/ in den Tempel gehen', 'Alkohol trinken', 'den Teller leer essen'];