let allTriggerAnswersJSON = `[
{"Sie müssen den Chef nicht anrufen." : ["Sie brauchen den Chef nicht anzurufen.", "Wieso brauche ich den Chef nicht anzurufen?", "Weil Sie den Chef nicht anrufen brauchen.", "Ich möchte den aber Chef anrufen."],
"Du musst das Auto nicht volltanken." : ["Du brauchst das Auto nicht vollzutanken.", "Wieso brauche ich das Auto nicht vollzutanken?", "Weil du das Auto nicht volltanken brauchst.", "Ich möchte das Auto aber volltanken."],
"Sie müssen kein Russisch lernen." : ["Sie brauchen kein Russisch zu lernen.", "Wieso brauche ich kein Russisch zu lernen?", "Weil Sie kein Russisch lernen brauchen.", "Ich möchte Russisch aber lernen."],
"Du musst heute nicht arbeiten." : ["Du brauchst heute nicht arbeiten.", "Wieso brauche ich heute nicht zu arbeiten?", "Weil du heute nicht arbeiten brauchst.", "Ich möchte heute aber  arbeiten."],
"Sie müssen die Schuhe nicht ausziehen." : ["Sie brauchen die Schuhe nicht auszuziehen.", "Wieso brauche ich die Schuhe nicht auszuziehen?", "Weil Sie die Schuhe nicht ausziehen brauchen.", "Ich möchte die Schuhe aber ausziehen."],
"Du musst kein Ticket kaufen." : ["Du brauchst kein Ticket zu kaufen.", "Wieso brauche ich kein Ticket zu kaufen?", "Weil du kein Ticket kaufen brauchst.", "Ich möchte ein Ticket aber  kaufen."],
"Sie müssen keinen neuen Computer kaufen." : ["Sie brauchen keinen neuen Computer zu kaufen.", "Wieso brauche ich keinen neuen Computer zu kaufen?", "Weil Sie keinen Computer kaufen brauchen.", "Ich möchte keinen Computer aber kaufen."],
"Du musst die Wohnung nicht putzen." : ["Du brauchst die Wohnung nicht zu putzen.", "Wieso brauche ich die Wohnung nicht zu putzen?", "Weil du die Wohnung nicht putzen brauchst.", "Ich möchte die Wohnung aber putzen."],
"Sie müssen keine dummen Fragen stellen." : ["Sie brauchen keine dummen Fragen zu stellen.", "Wieso brauche ich keine dummen Fragen zu stellen?", "Weil Sie keine dummen Fragen stellen brauchen.", "Ich möchte dumme Fragen aber stellen."],
"Du musst nicht auf mich warten." : ["Du brauchst nicht auf mich zu warten.", "Wieso brauche ich nicht auf dich zu warten?", "Weil du nicht auf mich warten brauchst.", "Ich möchte auf dich aber warten."]}
]`;

const triggers = ['Sie müssen den Chef nicht anrufen.', 'Du musst das Auto nicht volltanken.', 'Sie müssen kein Russisch lernen.', 'Du musst heute nicht arbeiten.', 'Sie müssen die Schuhe nicht ausziehen.', 'Du musst kein Ticket kaufen.', 'Sie müssen keinen neuen Computer kaufen.', 'Du musst die Wohnung nicht putzen.', 'Sie müssen keine dummen Fragen stellen.', 'Du musst nicht auf mich warten.'];