let allTriggerAnswersJSON = `[
{"gut/schlecht | Nachricht | Tag" : ["Ist das die beste Nachricht des ganzen Tages?", "Nein, das ist die schlechteste Nachricht des ganzen Tages.", "Warum ist das die schlechteste Nachricht des ganzen Tages?", "Weil es einfach die schlechteste Nachricht des ganzen Tages ist."],
"teuer/billig | Sauna | Viertel" : ["Ist das die teuerste Sauna des ganzen Viertels?", "Nein, das ist die billigste Sauna des ganzen Viertels.", "Warum ist das die billigste Sauna des ganzen Viertels?", "Weil es einfach die billigste Sauna des ganzen Viertels ist."],
"alt/modern | Haus | Stadt" : ["Ist das das älteste Haus der ganzen Stadt?", "Nein, das ist das modernste Haus der ganzen Stadt.", "Warum ist das das modernste Haus der ganzen Stadt?", "Weil es einfach das modernste Haus der ganzen Stadt ist."],
"dumm/intelligent | Idee | Besprechung" : ["Ist das die dümmste Idee der ganzen Besprechung?", "Nein, das ist die intelligenteste Idee der ganzen Besprechung.", "Warum ist das die intelligenteste Idee der ganzen Besprechung?", "Weil es einfach die intelligenteste Idee der ganzen Besprechung ist."],
"billig/teuer | Café | Kiez" : ["Ist das das billigste Café des ganzen Kiezes?", "Nein, das ist das teuerste Café des ganzen Kiezes.", "Warum ist das das teuerste Café des ganzen Kiezes?", "Weil es einfach das teuerste Café des ganzen Kiezes ist."],
"schlecht/gut | Restaurant | Land" : ["Ist das das schlechteste Restaurant des ganzen Landes?", "Nein, das ist das billigste Restaurant des ganzen Landes.", "Warum ist das das billigste Restaurant des ganzen Landes?", "Weil es einfach das billigste Restaurant des ganzen Landes ist."],
"inkompetent/kompetent | Mitarbeiterin | Firma" : ["Ist das der inkompetenteste Mitarbeiter der ganzen Firma?", "Nein, das ist der kompetenteste Mitarbeiter der ganzen Firma.", "Warum ist das der kompetenteste Mitarbeiter der ganzen Firma.", "Weil es einfach der kompetenteste Mitarbeiter der ganzen Firma ist."],
"aggressiv/lieb | Hund | Tierheim" : ["Ist das der aggressivste Hund des ganzen Tierheims?", "Nein, das ist der liebste Hund des ganzen Tierheims.", "Warum ist das der liebste Hund des ganzen Tierheims?", "Weil es einfach der liebste Hund des ganzen Tierheims ist."],
"langweilig/spannend |  Film | Filmfestival" : ["Ist das der langweiligste Film des ganzen Filmfestivals?", "Nein, das ist der spannendste Film des ganzen Filmfestivals.", "Warum ist das der spannendste Film des ganzen Filmfestivals?", "Weil es einfach der spannendste Film des ganzen Filmfestivals ist."],
"unbedeutend/bedeutend | Gemälde | Ausstellung" : ["Ist das das unbedeutendste Gemälde der ganzen Ausstellung?", "Nein, das ist das bedeutendste Gemälde der ganzen Ausstellung.", "Warum ist das das bedeutendste Gemälde der ganzen Ausstellung?", "Weil es einfach das bedeutendste Gemälde der ganzen Ausstellung ist."]}
]`;

const triggers = ['gut/schlecht | Nachricht | Tag', 'teuer/billig | Sauna | Viertel', 'alt/modern | Haus | Stadt', 'dumm/intelligent | Idee | Besprechung', 'billig/teuer | Café | Kiez', 'schlecht/gut | Restaurant | Land', 'inkompetent/kompetent | Mitarbeiterin | Firma', 'aggressiv/lieb | Hund | Tierheim', 'langweilig/spannend |  Film | Filmfestival', 'unbedeutend/bedeutend | Gemälde | Ausstellung'];