let allTriggerAnswersJSON = `[
{"sich kümmern um (+Akk.) | Kaninchen" : ["Kümmerst du dich um das Kaninchen?", "Ich kümmere mich nicht um das Kaninchen.", "Warum kümmerst du dich nicht um das Kaninchen?", "Weil ich mich nicht um das Kaninchen kümmere."],
"sich aufregen über (+Akk.) | Chefin" : ["Regst du dich über die Chefin auf?", "Ich rege mich nicht über die Chefin auf.", "Warum regst du dich nicht über die Chefin auf?", "Weil ich mich nicht über die Chefin aufrege."],
"sich ekeln vor (+Dat.) | Gestank" : ["Ekelst du dich vor dem Gestank?", "Ich ekel mich nicht vor dem Gestank.", "Warum ekelst du dich nicht vor dem Gestank?", "Weil ich mich nicht vor dem Gestank ekel."],
"sich verlieben in (+Akk.) | Nachbarin" : ["Verliebst du dich in die Nachbarin?", "Ich verliebe mich nicht in die Nachbarin.", "Warum verliebst du dich nicht in die Nachbarin?", "Weil ich mich nicht in die Nachbarin verliebe."],
"sich entscheiden füür (+Akk.) | love" : ["Entscheidest du dich für die Liebe?", "Ich entscheide mich nicht für die Liebe.", "Warum entscheidest du dich nicht für die Liebe?", "Weil ich mich nicht für die Liebe entscheide."],
"sich bedanken bei (+Dat.) | Papagei" : ["Bedankst du dich beim* Papagei? *(bei+dem = beim)", "Ich bedanke mich nicht beim Papagei.", "Warum bedankst du dich nicht beim Papagei?", "Weil ich mich nicht beim Papagei bedanke."],
"sich gewöhnen an (+Akk.) | Zustand" : ["Gewöhnst du dich an den Zustand?", "Ich gewöhne mich nicht an den Zustand.", "Warum gewöhnst du dich nicht an den Zustand?", "Weil ich mich nicht an den Zustand gewöhne."],
"sich erkundigen nach (+Dat.) | Oma" : ["Erkundigst du dich nach der Oma?", "Ich erkundige mich nicht nach der Oma.", "Warum erkundigst du dich nicht nach der Oma?", "Weil ich mich nicht nach der Oma erkundige."],
"sich freuen auf (+Akk.) | Urlaub" : ["Freust du dich auf den Urlaub?", "Ich freue mich nicht auf den Urlaub.", "Warum freust du dich nicht auf den Urlaub?", "Weil ich mich nicht auf den Urlaub freue."],
"sich schützen vor (+Dat) | Sonne" : ["Schützt du dich vor der Sonne?", "Ich schütze mich nicht vor der Sonne.", "Warum schützt du dich nicht vor der Sonne?", "Weil ich mich nicht vor der Sonne schütze."]}
]`;

const triggers = ['sich kümmern um (+Akk.) | Kaninchen', 'sich aufregen über (+Akk.) | Chefin', 'sich ekeln vor (+Dat.) | Gestank', 'sich verlieben in (+Akk.) | Nachbarin', 'sich entscheiden füür (+Akk.) | love', 'sich bedanken bei (+Dat.) | Papagei', 'sich gewöhnen an (+Akk.) | Zustand', 'sich erkundigen nach (+Dat.) | Oma', 'sich freuen auf (+Akk.) | Urlaub', 'sich schützen vor (+Dat) | Sonne'];