let allTriggerAnswersJSON = `[
{"Praktikant - lieben + beschäftigen" : ["Was macht ein Praktikant eigentlich so den ganzen Tag?", "Ein Praktikant liebt einen (anderen) Praktikanten.", "Einen Praktikanten liebt man doch nicht, man beschäftigt ihn.", "Da hast du wohl Recht."],
"Diplomat - begrüßen + empfangen" : ["Was macht ein Diplomat eigentlich so den ganzen Tag?", "Ein Diplomat begrüßt einen (anderen) Diplomaten.", "Einen Diplomaten begrüßt man doch nicht, man empfängt ihn.", "Da hast du wohl Recht."],
"Tourist - treffen + begegnen" : ["Was macht ein Tourist eigentlich so den ganzen Tag?", "Ein Tourist trifft einen (anderen) Touristen.", "Einen Touristen trifft man doch nicht, man begegnet ihm*.", "Da hast du wohl Recht."],
"Biologe - Kaffee trinken mit" : ["Was macht ein Biologe eigentlich den ganzen Tag?", "Ein Biologe trinkt mit einem (anderen) Biologen Kaffee.", "Mit einem Biologen trinkt man doch keinen Kaffee.", "Da hast du wohl Recht."],
"Bär -wecken + schlafen lassen" : ["Was macht ein Bär eigentlich den ganzen Tag?", "Ein Bär weckt einen anderen Bären.", "Einen Bären weckt man doch nicht, man lässt ihn schlafen.", "Da hast du wohl Recht."],
"Herr - spazieren gehen mit + mit ihm flanieren gehen" : ["Was macht ein Herr eigentlich den ganzen Tag?", "Ein Herr geht mit einem anderen Herrn spazieren.", "Mit einem Herrn geht man doch nicht spazieren. Mit einem Herrn geht man flanieren.", "Da hast du wohl Recht."],
"Nachbar - lästern über + her.ziehen über" : ["Was macht ein Nachbar eigentlich den ganzen Tag?", "Ein Nachbar lästert über einen anderen Nachbarn.", "Über einen Nachbarn lästert man nicht, man zieht über ihn her.", "Da hast du wohl Recht."],
"Mensch - an.lügen + jemandem die Wahrheit sagen" : ["Was macht ein Mensch eigentlich den ganzen Tag?", "Ein Mensch lügt einen anderen Menschen an.", "Einen Menschen lügt man nicht an, einem Menschen sagt man die Wahrheit.", "Da hast du wohl Recht."],
"Fotograf - fotografieren + ab.lichten" : ["Was macht ein Fotograf eigentlich den ganzen Tag?", "Ein Fotograf fotografiert einen Fotografen.", "Einen Fotografen fotografiert man doch nicht, man lichtet ihn ab.", "Da hast du wohl Recht."],
"Journalist - schreiben über + berichten über" : ["Was macht ein Journalist eigentlich den ganzen Tag?", "Ein Journalist schreibt über einen Journalisten.", "Über einen Journalisten schreibt man nicht, man berichtet über ihn.", "Da hast du wohl Recht."],
"Franzose - sprechen mit + man tauscht sich mit aus" : ["Was macht ein Franzose eigentlich den ganzen Tag?", "Ein Franzose spricht mit einem Franzosen.", "Mit einem Franzosen spricht man nicht, man tauscht sich mit ihm aus.", "Da hast du wohl Recht."]}
]`;

const triggers = ['Praktikant - lieben + beschäftigen', 'Diplomat - begrüßen + empfangen', 'Tourist - treffen + begegnen', 'Biologe - Kaffee trinken mit', 'Bär -wecken + schlafen lassen', 'Herr - spazieren gehen mit + mit ihm flanieren gehen', 'Nachbar - lästern über + her.ziehen über', 'Mensch - an.lügen + jemandem die Wahrheit sagen', 'Fotograf - fotografieren + ab.lichten', 'Journalist - schreiben über + berichten über', 'Franzose - sprechen mit + man tauscht sich mit aus'];