let allTriggerAnswersJSON = `[
{"regnen - zu Hause bleiben" : ["Wenn es regnet, bleibe ich zu Hause.", "Wenn es regnen würde, würde ich zu Hause bleiben.", "Wenn es geregnet hätte, wäre ich zu Hause geblieben.", "Aber es hat nicht geregnet."],
"arbeiten - Geld verdienen" : ["Wenn ich arbeite, verdiene ich Geld.", "Wenn ich arbeiten würde, würde ich Geld verdienen.", "Wenn ich gearbeitet hätte, hätte ich Geld verdient.", "Aber ich habe nicht gearbeitet."],
"verschlafen - zu spät kommen" : ["Wenn ich verschlafe, komme ich zu spät.", "Wenn ich verschlafen würde, würde ich zu spät kommen.", "Wenn ich verschlafen hätte, wäre ich zu spät gekommen.", "Aber ich habe nicht verschlafen."],
"nicht im Unterricht aufpassen - nichts lernen" : ["Wenn ich nicht im Unterricht aufpasse, lerne ich nichts.", "Wenn ich im Unterricht nicht aufpassen würde, würde ich nichts lernen.", "Wenn ich im Unterricht nicht aufgepasst hätte, hätte ich nichts gelernt.", "Aber ich habe im Unterricht aufgepasst."],
"den Zug verpassen - den nächsten Zug nehmen" : ["Wenn ich den Zug verpasse, nehme ich den nächsten Zug.", "Wenn ich den Zug verpassen würde, würde ich den nächsten Zug nehmen.", "Wenn ich den Zug verpasst hätte, hätte ich den nächsten Zug genommen.", "Aber ich habe den Zug nicht verpasst."],
"frei haben* - den Tag genießen" : ["Wenn ich frei habe, genieße ich den Tag.", "Wenn ich frei hätte, würde ich den Tag genießen.", "Wenn ich frei gehabt hätte, hätte ich den Tag genossen.", "Aber ich habe nicht frei gehabt."],
"zu Hause sein - nackig rumlaufen" : ["Wenn ich zu Hause bin, laufe ich nackig rum.", "Wenn ich zu Hause wäre, würde ich nackig rumlaufen.", "Wenn ich zu Hause gewesen wäre, wäre ich nackig rumgelaufen.", "Aber ich bin nicht zu Hause gewesen."],
"kein Gehalt bekommen - aufhören zu arbeiten" : ["Wenn ich kein Geld bekomme, höre ich auf zu arbeiten.", "Wenn ich kein Geld bekommen würde, würde ich aufhören zu arbeiten.", "Wenn ich kein Geld bekommen hätte, hätte ich aufgehört zu arbeiten.", "Aber ich habe Geld bekommen."],
"sich einen Hund anschaffen - sich darum kümmern" : ["Wenn ich mir einen Hund anschaffe, kümmere ich mich darum.", "Wenn ich mir einen Hund anschaffen würde, würde ich mich darum kümmern.", "Wenn ich mir einen Hund angeschafft hätte, hätte ich mich darum gekümmert.", "Aber ich habe mir keinen Hund angeschafft."],
"Urlaub haben - sich entspannen" : ["Wenn ich Urlaub habe, entspanne ich mich.", "Wenn ich Urlaub hätte, würde ich mich entspannen.", "Wenn ich Urlaub gehabt hätte, hätte ich mich entspannt.", "Aber ich habe keinen Urlaub gehabt."],
"Alkohol trinken - anzüglich werden" : ["Wenn ich Alkohol trinke, werde ich anzüglich.", "Wenn ich Alkohol trinken würde, würde ich anzüglich werden.", "Wenn ich Alkohol getrunken hätte, wäre ich anzüglich geworden.", "Aber ich habe keinen Alkohol getrunken."]}
]`;

const triggers = ['regnen - zu Hause bleiben', 'arbeiten - Geld verdienen', 'verschlafen - zu spät kommen', 'nicht im Unterricht aufpassen - nichts lernen', 'den Zug verpassen - den nächsten Zug nehmen', 'frei haben* - den Tag genießen', 'zu Hause sein - nackig rumlaufen', 'kein Gehalt bekommen - aufhören zu arbeiten', 'sich einen Hund anschaffen - sich darum kümmern', 'Urlaub haben - sich entspannen', 'Alkohol trinken - anzüglich werden'];