let allTriggerAnswersJSON = `[
{"zwei Brüder - älter ≠ jünger" : ["Ich habe zwei Brüder.", "Ein Bruder ist jünger als ich. Das ist mein jüngerer Bruder.", "Ein Bruder ist älter als ich. Das ist mein älterer Bruder.", "Ich habe also einen jüngeren und einen älteren Bruder."],
"zwei Kinder - einfacher ≠ schwieriger" : ["Ich habe zwei Kinder.", "Ein Kind ist einfacher als das andere. Das ist mein einfacheres Kind.", "Ein Kind ist schwieriger als das andere. Das ist mein schwierigeres Kind.", "Ich habe also ein einfacheres und ein schwierigeres Kind."],
"zwei Katzen - zahmer ≠ wilder" : ["Ich habe zwei Katzen.", "Eine Katze ist zahmer als die andere. Das ist meine zahmere Katze.", "Eine Katze ist wilder als die andere. Das ist meine wildere Katze.", "Ich habe also eine zahmere und eine wildere Katze."],
"zwei Schwestern - groß≠klein" : ["Ich habe zwei Schwestern.", "Eine Schwester ist größer als ich. Das ist meine größere Schwester.", "Eine Schwester ist kleiner als ich. Das ist meine kleinere Schwester.", "Ich habe also eine größere und eine kleinere Schwester."],
"zwei Sofas - bequem≠/unbequem" : ["Ich habe zwei Sofas.", "Ein Sofa ist bequemer als das andere. Das ist mein bequemeres Sofa.", "Ein Sofa ist unbequemer als das andere. Das ist mein unbequemeres Sofa.", "Ich habe also ein bequemeres und ein unbequemeres Sofa."],
"zwei Arme - lang≠kurz" : ["Ich habe zwei Arme.", "Ein Arm ist länger als der andere. Das ist mein längerer Arm.", "Ein Arm ist kürzer als der andere. Das ist mein kürzerer Arm.", "Ich habe also einen längeren und einen kürzeren Arm."],
"zwei Nachbarn - ruhig≠laut" : ["Ich habe zwei Nachbarn.", "Ein Nachbar ist ruhiger als der andere. Das ist mein ruhigerer Nachbar.", "Ein Nachbar ist lauter als der andere. Das ist mein lauterer Nachbar.", "Ich habe also einen ruhigeren und einen lauteren Nachbarn."],
"zwei Freunde - zuverlässig≠unzuverlässig" : ["Ich habe zwei Freunde.", "Ein Freund ist zuverlässiger als der andere. Das ist mein zuverlässigerer Freund.", "Ein Freund ist unzuverlässiger als der andere. Das ist mein unzuverlässigerer Freund.", "Ich habe also einen zuverlässigeren und einen unzuverlässigeren Freund."],
"zwei Söhne - erfolgreich≠erfolglos" : ["Ich habe zwei Söhne.", "Ein Sohn ist erfolgreicher als der andere. Das ist mein erfolgreicherer Sohn.", "Ein Sohn ist erfolgloser als der andere. Das ist mein erfolgloserer Sohn.", "Ich habe also einen erfolgreicheren und einen erfolgloseren Sohn."],
"zwei Kollegen - fleißig≠faul" : ["Ich habe zwei Kollegen.", "Ein Kollege ist fleißiger als der andere. Das ist mein fleißigerer Kollege.", "Ein Kollege ist fauler als der andere. Das ist mein faulerer Kollege.", "Ich habe also einen fleißigeren und einen fauleren Kollege."],
"zwei Lampen - hell≠dunkel" : ["Ich habe zwei Lampen.", "Eine Lampe ist heller als die andere. Das ist meine hellere Lampe.", "Eine Lampe ist dunkler als die andere. Das ist meine dunklere Lampe.", "Ich habe also eine hellere und eine dunklere Lampe."],
"zwei Taschen - modern≠altmodisch" : ["Ich habe zwei Taschen.", "Eine Tasche ist moderner als die andere. Das ist meine modernere Tasche.", "Eine Tasche ist altmodischer als die andere. Das ist meine altmodischere Tasche.", "Ich habe also eine modernere und eine altmodischere Tasche."]}
]`;

const triggers = ['zwei Brüder - älter ≠ jünger', 'zwei Kinder - einfacher ≠ schwieriger', 'zwei Katzen - zahmer ≠ wilder', 'zwei Schwestern - groß≠klein', 'zwei Sofas - bequem≠/unbequem', 'zwei Arme - lang≠kurz', 'zwei Nachbarn - ruhig≠laut', 'zwei Freunde - zuverlässig≠unzuverlässig', 'zwei Söhne - erfolgreich≠erfolglos', 'zwei Kollegen - fleißig≠faul', 'zwei Lampen - hell≠dunkel', 'zwei Taschen - modern≠altmodisch'];