let allTriggerAnswersJSON = `[
{"Ich habe Hunger. (mein Hunger) - nicht essen" : ["Obwohl ich Hunger habe, esse ich nicht.", "Trotz meinem Hunger esse ich nicht.", "Trotz meines Hungers esse ich nicht.", "Ich habe Hunger. Trotzdem esse ich nicht."],
"Ich habe viel Geld. (mein Geld) - nicht glücklich sein" : ["Obwohl ich viel Geld habe, bin ich nicht glücklich.", "Trotz meinem vielen Geld bin ich nicht glücklich.", "Trotz meines vielen Geldes bin ich nicht glücklich.", "Ich habe viel Geld. Trotzdem bin ich nicht glücklich."],
"Ich bin müde. (meine Müdigkeit) - nicht ins Bett gehen" : ["Obwohl ich müde bin, gehe ich nicht ins Bett.", "Trotz meiner Müdigkeit gehe ich nicht ins Bett.", "Trotz meiner Müdigkeit gehe ich nicht ins Bett.", "Ich bin müde. Trotzdem gehe ich nicht ins Bett."],
"Ich habe Asthma. (mein Asthma) - rauchen" : ["Obwohl ich Asthma habe, rauche ich.", "Trotz meinem Asthma rauche ich.", "Trotz meines Asthmas rauche ich.", "Ich habe Asthma. Trotzdem rauche ich."],
"Es ist kalt. (die Kälte) - kurze Hosen tragen" : ["Obwohl es kalt ist, trage ich kurze Hosen.", "Trotz der Kälte trage ich kurze Hosen.", "Trotz der Kälte trage ich kurze Hosen.", "Es ist kalt. Trotzdem trage ich kurze Hosen."],
"Er hat 10 Kilo abgenommen. (sein Gewichtsverlust) - seine Frau verlässt ihn" : ["Obwohl er 10 Kilo abgenommen hat, verlässt ihn seine Frau.", "Trotz seinem Gewichtsverlust verlässt ihn seine Frau.", "Trotz seines Gewichtsverlustes verlässt ihn seine Frau.", "Er hat 10 Kilo abgenommen. Trotzdem verlässt ihn seine Frau."],
"Er ist intelligent. (seine Intelligenz) - sich immer in die falsche Frau verlieben" : ["Obwohl er intelligent ist, verliebt er sich immer in die falsche Frau.", "Trotz seiner Intelligenz verliebt er sich immer in die falsche Frau.", "Trotz seiner Intelligenz verliebt er sich immer in die falsche Frau.", "Er ist intelligent. Trotzdem verliebt er sich immer in die falsche Frau."],
"Das neue Schreiphone ist sehr teuer. (der hohe Preis) - Viele Leute kaufen es." : ["Obwohl das neue Iphone sehr teuer ist, kaufen viele Leute es.", "Trotz dem hohen Preis kaufen viele Leute es", "Trotz des hohen Preises kaufen viele Leute es.", "Das neue Iphone ist sehr teuer. Trotzdem kaufen viele Leute es."],
"Die Musik ist nicht laut. (die niedrige Lautstärke). - Sie stört mich." : ["Obwohl die Musik nicht laut ist, stört sie mich.", "Trotz der niedrigen Lautstärke stört sie mich.", "Trotz der niedrigen Lautstärke stört sie mich.", "Die Musik ist nicht laut. Trotzdem stört sie mich."],
"Sie waren beim Friseur. (ihr Friseurbesuch) - Sie sehen immer noch fürchterlich aus." : ["Obwohl sie beim Friseur waren, sehen sie fürchterlich aus.", "Trotz ihrem Friseurbesuch sehen sie fürchterlich aus.", "Trotz ihres Friseurbesuchs sehen sie fürchterlich aus.", "Sie waren beim Friseur. Trotzdem sehen sie fürchterlich aus."]}
]`;

const triggers = ['Ich habe Hunger. (mein Hunger) - nicht essen', 'Ich habe viel Geld. (mein Geld) - nicht glücklich sein', 'Ich bin müde. (meine Müdigkeit) - nicht ins Bett gehen', 'Ich habe Asthma. (mein Asthma) - rauchen', 'Es ist kalt. (die Kälte) - kurze Hosen tragen', 'Er hat 10 Kilo abgenommen. (sein Gewichtsverlust) - seine Frau verlässt ihn', 'Er ist intelligent. (seine Intelligenz) - sich immer in die falsche Frau verlieben', 'Das neue Schreiphone ist sehr teuer. (der hohe Preis) - Viele Leute kaufen es.', 'Die Musik ist nicht laut. (die niedrige Lautstärke). - Sie stört mich.', 'Sie waren beim Friseur. (ihr Friseurbesuch) - Sie sehen immer noch fürchterlich aus.'];